name: Build Application

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # .jar file
  build_jar_file:
    name: Build Jar File
    runs-on: ubuntu-latest
    env:
      OUTPUT: es_shipyard.jar
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: true
      - name: Build Application
        run: |
          javac *.java
          jar -cfe es_shipyard.jar Shipyard *.class
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.OUTPUT }}

  # Application-specific files
  build_exe_file:
    name: Build Executable
    runs-on: windows-2025
    env:
      OUTPUT: es_shipyard_windows.exe
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: true
      - name: Install Dependencies
        run: |
          npm install -g pkg
      - name: Build Application
        run: |
          javac *.java
          jar -cfe es_shipyard_windows.jar Shipyard *.class
          pkg es_shipyard_windows.exe 
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT }}
          path: ${{ env.OUTPUT }}

  # build_ubuntu_file:
  #   name: Linux
  #   runs-on: ubuntu-22.04
  #   env:
  #     OUTPUT: es_shipyard_linux.jar
  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         show-progress: true
  #     - name: Build Application
  #       run: |
  #         javac *.java
  #         jar -cfe es_shipyard_linux.jar Shipyard *.class
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ${{ env.OUTPUT }}
  #         path: ${{ env.OUTPUT }}

  # build_application:
  #   name: MacOS
  #   runs-on: macos-13
  #   env:
  #     OUTPUT: es_shipyard_macos.jar
  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         show-progress: true
  #     - name: Build Application
  #       run: |
  #         javac *.java
  #         jar -cfe es_shipyard_macos.jar Shipyard *.class
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ${{ env.OUTPUT }}
  #         path: ${{ env.OUTPUT }}

  cd_upload_artifacts_to_release:
    name: Upload
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - build_exe_file
      - build_jar_file
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OUTPUT_JAR_FILE: es_shipyard.jar
      OUTPUT_EXE_FILE: es_shipyard_windows.exe
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: true
      - name: Install github-release
        run: |
          go install github.com/github-release/github-release@latest
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Set environment variables
        run: |
          echo "GITHUB_USER=$( echo ${{ github.repository }} | cut -d/ -f1 )" >> $GITHUB_ENV
          echo "GITHUB_REPO=$( echo ${{ github.repository }} | cut -d/ -f2 )" >> $GITHUB_ENV
      - name: Move/Create continuous tag
        run: |
          git tag --force continuous ${{ github.sha }}
          git push --tags --force
      - name: Setup continuous release
        run: |
          DESCRIPTION="Triggered on $(date -u '+%Y/%m/%d, %H:%M') UTC by commit ${{ github.sha }} (@${{ github.actor }})

          This is an automated build of the latest source. It has not been tested and may cause problems. Use with caution!

          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          if ! github-release info -t continuous > /dev/null 2>&1; then
            github-release release \
              --tag continuous \
              --name "Continuous Build" \
              --description "$DESCRIPTION" \
              --pre-release
          else
            github-release edit \
              --tag continuous \
              --name "Continuous Build" \
              --description "$DESCRIPTION" \
              --pre-release
          fi
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}
      # - name: Add ${{ env.OUTPUT_APPIMAGE }} to release tag
      #   continue-on-error: true
      #   run: |
      #     github-release upload \
      #       --tag continuous \
      #       --replace \
      #       --name ${{ env.OUTPUT_APPIMAGE }} \
      #       --file ${{ env.OUTPUT_APPIMAGE }}/${{ env.OUTPUT_APPIMAGE }}
      - name: Add ${{ env.OUTPUT_EXE_FILE }} to release tag
        continue-on-error: true
        run: |
          github-release upload \
            --tag continuous \
            --replace \
            --name ${{ env.OUTPUT_EXE_FILE }} \
            --file ${{ env.OUTPUT_EXE_FILE }}/${{ env.OUTPUT_EXE_FILE }}
      - name: Add ${{ env.OUTPUT_JAR_FILE }} to release tag
        continue-on-error: true
        run: |
          github-release upload \
            --tag continuous \
            --replace \
            --name ${{ env.OUTPUT_JAR_FILE }} \
            --file ${{ env.OUTPUT_JAR_FILE }}/${{ env.OUTPUT_JAR_FILE }}
      # - name: Add ${{ env.OUTPUT_MACOS }} to release tag
      #   run: |
      #     github-release upload \
      #       --tag continuous \
      #       --replace \
      #       --name ${{ env.OUTPUT_MACOS }} \
      #       --file ${{ env.OUTPUT_MACOS }}/${{ env.OUTPUT_MACOS }}
